# levels of logging: "local"; "local_info"; "prod"
env: "local"

ctx_timeout: 8s

psql_storage:
  db_driver: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "command_api"
  user: "postgres"
  sslmode: "disable"

api_server:
  address: "0.0.0.0:8008"
  timeout: 4s
  idle_timeout: 600s

frontend:
  domains: ["http://localhost:3003"]